//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HospitalManagament
{
    using System;
    using System.Collections.Generic;
    
    public partial class LoginAttempt
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public LoginAttempt()
        {
            this.IsPassed = false;
        }
    
        public long Id { get; set; }
        public string Email { get; set; }
        public string Password { get; set; }
        public Nullable<bool> IsPassed { get; set; }
        public Nullable<System.DateTime> AttemptDateTime { get; set; }
        public string IpAddress { get; set; }
    }
}
